// <auto-generated />
using System;
using Final.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final.Web.Migrations
{
    [DbContext(typeof(DbContextFinal))]
    [Migration("20191130191324_ExFinal_Damaso_5")]
    partial class ExFinal_Damaso_5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Final.Entidades.Departamento", b =>
                {
                    b.Property<int>("iddepartamento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Visitaidvisita");

                    b.Property<bool>("estado");

                    b.Property<string>("nombre")
                        .HasMaxLength(100);

                    b.HasKey("iddepartamento");

                    b.HasIndex("Visitaidvisita");

                    b.ToTable("departamento");
                });

            modelBuilder.Entity("Final.Entidades.Persona", b =>
                {
                    b.Property<int>("idpersona")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Visitaidvisita");

                    b.Property<string>("apellido")
                        .HasMaxLength(100);

                    b.Property<string>("correo");

                    b.Property<string>("direccion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("telefono");

                    b.HasKey("idpersona");

                    b.HasIndex("Visitaidvisita");

                    b.ToTable("persona");
                });

            modelBuilder.Entity("Final.Entidades.Visita", b =>
                {
                    b.Property<int>("idvisita")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Persona");

                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<TimeSpan>("hora_entrada");

                    b.Property<TimeSpan>("hora_salida");

                    b.Property<string>("motivo");

                    b.HasKey("idvisita");

                    b.ToTable("visita");
                });

            modelBuilder.Entity("Final.Entidades.Departamento", b =>
                {
                    b.HasOne("Final.Entidades.Visita")
                        .WithMany("departamento")
                        .HasForeignKey("Visitaidvisita");
                });

            modelBuilder.Entity("Final.Entidades.Persona", b =>
                {
                    b.HasOne("Final.Entidades.Visita")
                        .WithMany("personas")
                        .HasForeignKey("Visitaidvisita");
                });
#pragma warning restore 612, 618
        }
    }
}
